### ISSUE TITLE
How can I get the full positions of the other agents in the same frame?

### ISSUE THREAD

**Issue by idevede** [lyft/l5kit#107]
We have noticed that the input information is included in a image format. What if we want to use the position information of other agents in the same frame. We think that the interactive information of each agents can bring great improvement.

**Comment by lucabergamini** [comment]
Hi @idevede, as far as I've understood (please correct me if I'm wrong) you would like to:
- get the history (and maybe also future) position displacements for all the agents in a given frame while you're centred on one of those agents

Our toolkit is mainly designed for BEV approaches (images for a CNN), so we currently don't export API for something like this OOB. However:
- you can use `AgentDataset.get_frame_indices` to return all the index of the agents for a given frame;
- you can pass them to the same `AgentDataset` to get the data for each agent, which includes history and future displacement (if you're not interested into BEV you can just use a `stub_debug` rasterizer which just returns a black image)
- you can transform them into the same space using the `world_to_image` matrix of you reference agent (remember to first sum the centroid coordinates as displacements are relative)

It's a quite complex pipeline, and the main issue is probably that you won't be able to parallelise it into a DataLoader easily.

However, also supporting agents displacements directly from the Dataset object is quite tricky, as the number of agents is far from being fixed (we would need a custom `collate_function` to handle it)

Sorry for the long reply, does this answer your question?

**Comment by idevede** [comment]
That does answer our question, and it looks like the process is a little bit complicated, thank you for such a long reply.

**Comment by lucabergamini** [comment]
np, if you put together an easier solution feel free to start a PR :) Otherwise, I may pick this up again when I have some free cycles
