### ISSUE TITLE
Functionality to allow Ego/Agent-Dataset to not have a rasterizer

### ISSUE THREAD

**Issue by joseluisvaz** [lyft/l5kit#116]
Would it be possible to add the functionality to not use a rasterizer in `EgoDataset`? This could speed up the data loading and given that some solutions will only use `data["history_positions"]` sometimes generating the images just adds computational overhead.

**Comment by lucabergamini** [comment]
Closing this now as `stub_debug` can be used as a low-overhead option for now.
