### ISSUE TITLE
ValueError: group not found at path '' Error

### ISSUE THREAD

**Issue by rajeshpaulnadar** [lyft/l5kit#127]
Dear Team,

As you have described in the 'Download the datasets' section, I have kept the aerial,semantic maps and scenes sub folders and json file.

I am getting following error , when I ran the file visualise_data.ipynb.
** Error code section :**
dm = LocalDataManager()
dataset_path = dm.require(cfg["val_data_loader"]["key"])
zarr_dataset = ChunkedDataset(dataset_path)
zarr_dataset.open()
print(zarr_dataset)

"Error message"
![image](https://user-images.githubusercontent.com/39669265/91482568-e23aea00-e8c3-11ea-91a2-38248f3cb191.png)

Could you please provide the solution for this issue..

Thanks and regards,
Rajesh Paul

**Comment by lucabergamini** [comment]
Hi @rajeshpaulnadar,

Can you check if the path in `dataset_path ` exists on your disk? Just adding a print for it before creating the `ChunkedDataset` will do

**Comment by rajeshpaulnadar** [comment]
Hello @lucabergamini 

Thank you for your reply.
I have downloaded the sample.zarr file again and tried. 
there is no error now, I am able to visualize the data.

with regards,
Rajesh
