### ISSUE TITLE
How to train using Tensorflow

### ISSUE THREAD

**Issue by sarthakforwet** [lyft/l5kit#131]
I am currently working on Lyft's kaggle competition to predict the motion of AV. All the models there are implemented using pytorch, however I usually work in tensorflow and want to know how I can prepare a tensorflow model for this task. Thanks!

**Comment by lucabergamini** [comment]
Hi @sarthakforwet ,
L5Kit `dataset` package was designed to work with PyTorch only. 
Converting it to tensorflow is probably feasible (I'm not a tensorflow user though so I can't estimate the total effort) but it's not on our roadmap right now. 
Clearly, if anyone want to start a PR to support it, I'm happy to review it :)
