### ISSUE TITLE
bug in agent sampling?

### ISSUE THREAD

**Issue by jmercat** [lyft/l5kit#137]
I found this line in the file l5kit/l5kit/l5kit/sampling/agent_sampling.py line 193, "agents" is both the iterated element and the list on which the loop is done. I'm not sure what this means but this should probably be corrected.

`for i, (frame, agents) in enumerate(zip(frames, agents)):`

**Comment by lucabergamini** [comment]
Interesting! It's actually weird everything has been working properly, I'll dig into into it!

**Comment by lucabergamini** [comment]
So it turned out this is perfectly legal in Python (see #141 ). Still, we're addressing it for clarity :) I'll change the label to `enhancement`.

**Comment by lucabergamini** [comment]
#141 has been merged into master, closing this now :)
