### ISSUE TITLE
Duplicate Tack Id in the same frame

### ISSUE THREAD

**Issue by Mrmoore98** [lyft/l5kit#138]
When I processing the sample dataset found that there are duplicate track Ids in the same frame, and the attribute value of them are not same.

```
array([([  671.78094482, -2196.83374023], [0.6011633 , 1.2727729 , 0.38642073], 0.99196154, [4.2793603, 7.436639 ], 1, [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
       ([  672.21514893, -2196.10375977], [0.6011633 , 1.2727729 , 0.38642073], 0.9913136 , [4.2783957, 7.4371986], 1, [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])],
      dtype=[('centroid', '<f8', (2,)), ('extent', '<f4', (3,)), ('yaw', '<f4'), ('velocity', '<f4', (2,)), ('track_id', '<u8'), ('label_probabilities', '<f4', (17,))])
```

timestamp is 1572643685901838786

**Comment by Mrmoore98** [comment]
@lucabergamini

**Comment by lucabergamini** [comment]
Should be easy to debug, I'll get back as soon as I have some news on this :)

**Comment by lucabergamini** [comment]
@Mrmoore98 I don't see any duplicates for that frame. I got 75 agents all with different ids.
Can you include here the code you're using to read the agents for that frame? If you're on master we have a handy util for that [here](https://github.com/lyft/l5kit/blob/022d829ddd497b6bcbc7c910dd0b3067b34b29fb/l5kit/l5kit/data/filter.py#L136)

**Comment by Mrmoore98** [comment]
I will go back and check my code and data later, the code I used is exactly same with the code you refered.
In addition the data I used was downloaded 14 days ago.

**Comment by Mrmoore98** [comment]
sorry to waste your time .
It seems that the preprocess code I used introduce some bugs which changes the raw data.

**Comment by lucabergamini** [comment]
np :)
