### ISSUE TITLE
regarding agent_sampling

### ISSUE THREAD

**Issue by ramicetty** [lyft/l5kit#146]
Team, when I am debugging l5kit, I found something but I am not sure it's functionally correct or not.  Kindly ignore if it won't make sense

At the time of [agent sampling](https://github.com/lyft/l5kit/blob/master/l5kit/l5kit/sampling/agent_sampling.py#L73), I can see that you are slicing history and future frames based on the number_of_frames (interested) and step_size (-ve value for history and +ve value for future).
Ex:

```
list_of_frame_index_of_scene = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
interested_current_state_index = 4
step_size = 2
number_of_frames_interested_states = 2
#then
history_and_future_frames_of_current_state_index = [0, 2, 4, 6, 8]
```
At the time of [getting agents](https://github.com/lyft/l5kit/blob/master/l5kit/l5kit/data/filter.py#L136) by using agent_intervals which are available in frames, You are sequentially parsing by looking at the starting index available at the first frame and the ending index at the last frame in the given frame_array(s).

But this may not true for frame_array which I made based on step_size right? because some frames(state) are missing between.
or You are assuming that agents available at the first frame and last frame in a given array can be the same?

We had a discussion [here]( https://www.kaggle.com/c/lyft-motion-prediction-autonomous-vehicles/discussion/181751) already. Please refer.

**Comment by lucabergamini** [comment]
I'll try to pick this up ASAP, sorry for the late reply :)

**Comment by lucabergamini** [comment]
The current situation is that even if we support `history_step_size` and `future_step_size` in config, those are not really supported in the full codebase.

We're discussing right now how to address this. We could either remove these options entirely (I don't think a lot of users are using it) or fully support them. For the latter I presume it won't happen anytime soon, as it's not considered a top priority atm.

**Comment by lucabergamini** [comment]
`step_size` greater than 1 has been officially removed from the codebase because of lack of usages and support :) #213
