### ISSUE TITLE
AgentDataset with rasterizer set to None

### ISSUE THREAD

**Issue by ahmed-h-elsheikh** [lyft/l5kit#149]
Code crashes when `rasterizer` is set to `None` as a special case for handling `data["image"]=None` is missing in line 84  `ego.py` --> see specific error below
```
l5kit/dataset/ego.py in get_frame(self, scene_index, state_index, track_id)
     82         data = self.sample_function(state_index, frames, self.dataset.agents, self.dataset.tl_faces, track_id)
     83         # 0,1,C -> C,0,1
---> 84         image = data["image"].transpose(2, 0, 1)
```

**Comment by lucabergamini** [comment]
Hey @ahmed-h-elsheikh are you on master or some released version?
We have an option (`stub_debug`) you can use into `build_rasterizer` to get an empty tensor each time.

**Comment by lucabergamini** [comment]
`stub_debug` is now available also in the latest release. I'll close this one for now
