### ISSUE TITLE
Add support for pytorch1.6

### ISSUE THREAD

**Issue by sanch7** [lyft/l5kit#154]
Would like to see support for PyTorch 1.6 and torchvision 0.7.

**Comment by lucabergamini** [comment]
Hi @sanch7,
Due to some internal projects depending on l5kit we still cannot bump the version officially. Still, nothing prevents you from installing 1.6 on top of the l5kit installation. I'm not aware of any breaking changes in torch between 1.5 and 1.6, so I expect it to work.
