### ISSUE TITLE
Error while visualization. 

### ISSUE THREAD

**Issue by CloudedLeopard17** [lyft/l5kit#161]
Hello Team, I am getting an "Argument radius is required to be an integer"  error while visualizing the scenes. 
![lyft-error](https://user-images.githubusercontent.com/33505589/94637527-73ebac00-02f5-11eb-9cfa-0403b2c1adc7.png)

**Comment by lucabergamini** [comment]
Hey @CloudedLeopard17 are you running a custom script or one of the examples? We changed that function API (see [here](https://github.com/lyft/l5kit/blob/082359ae88a53326e6693568760815597e364054/l5kit/l5kit/visualization/utils.py#L44)) in the latest release

**Comment by pascal-pfeiffer** [comment]
The yaws are now the 5th argument and no longer the 3rd argument for the drawing function.

The new API call must now be something like this:
`draw_trajectory(image, positions_pixels, TARGET_POINTS_COLOR, radius=1, yaws=data["target_yaws"])`
