### ISSUE TITLE
Error when using chopped dataset function

### ISSUE THREAD

**Issue by suryajayaraman** [lyft/l5kit#180]
Hi,

I'm trying to reproduce the model validation part in [l5kit reference notebook](https://github.com/lyft/l5kit/blob/master/examples/agent_motion_prediction/agent_motion_prediction.ipynb) locally. I have extracted the data (kaggle data ~22GB) locally and using a conda environment (Ubuntu 16.04, Python 3.6, l5kit version 1.1.0) to run validation. But when using the create_chopped_dataset function, I get the following error. 

![l5kit_zarr_error](https://user-images.githubusercontent.com/17627202/95947057-711bab80-0e0b-11eb-9b82-08346081e1af.png)

Any help would be most welcome.

**Comment by lucabergamini** [comment]
Hey @suryajayaraman 
Note that we've recently dropped support for python 3.6, so it's possible some operations may not work as expected there.
However, you error seems more related with corrupted files, have you tried to download again the data?

**Comment by suryajayaraman** [comment]
Hi,

Thanks for the support @lucabergamini, somehow my files were broken and downloading again solved the issue.
