### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by abhinaythurlapati** [lyft/l5kit#183]
Could you please look at this issue
pip3 install l5kit
Collecting l5kit
  Using cached l5kit-1.1.0-py3-none-any.whl (82 kB)
Requirement already satisfied: protobuf>=3.12.2 in c:\users\xxxxx\miniconda3\lib\site-packages (from l5kit) (3.13.0)
Requirement already satisfied: tqdm in c:\users\xxxxx\miniconda3\lib\site-packages (from l5kit) (4.48.2)
Collecting transforms3d
  Downloading transforms3d-0.3.1.tar.gz (62 kB)
     |████████████████████████████████| 62 kB 6.4 kB/s
Requirement already satisfied: pyyaml in c:\users\xxxx\miniconda3\lib\site-packages (from l5kit) (5.3.1)
Collecting zarr
  Downloading zarr-2.5.0-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 3.3 MB/s
Requirement already satisfied: notebook in c:\users\xxxxx\miniconda3\lib\site-packages (from l5kit) (6.1.1)
Requirement already satisfied: setuptools in c:\users\xxxxxx\miniconda3\lib\site-packages (from l5kit) (49.6.0.post20200814)
ERROR: Could not find a version that satisfies the requirement torchvision<1.0.0,>=0.6.0 (from l5kit) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.1, 0.5.0)
ERROR: No matching distribution found for torchvision<1.0.0,>=0.6.0 (from l5kit)

**Comment by lucabergamini** [comment]
This is a known issue with Windows. You can try to follow the developer workflow from [our guide](https://github.com/lyft/l5kit#installing-as-a-developer) (see Windows installation notes). Alternatively, you should be able to provide the link to torch by running:
`pip3 install l5kit --find-links https://download.pytorch.org/whl/torch_stable.html` (but I haven't test it)

**Comment by abhinaythurlapati** [comment]
> This is a known issue with Windows. You can try to follow the developer workflow from [our guide](https://github.com/lyft/l5kit#installing-as-a-developer) (see Windows installation notes). Alternatively, you should be able to provide the link to torch by running:
> `pip3 install l5kit --find-links https://download.pytorch.org/whl/torch_stable.html` (but I haven't test it)
Started with the second approach using 'find-links'. This smoothly installed torchvision-0.7 followed by l5kit. Thank You!
