### ISSUE TITLE
l5kit getting stuck during load_agents_mask

### ISSUE THREAD

**Issue by dodler** [lyft/l5kit#184]
i'm trying to create AgentDataset, but seem's like it's getting stuck here

AgentDataset -> load_agents_mask -> convenience.load

![image](https://user-images.githubusercontent.com/6881262/97026993-cde13980-1562-11eb-95cd-dfd6c0e92ca8.png) - this seem's to be script with AgentDataset

what can i do with this?

**Comment by lucabergamini** [comment]
Which set are you working with? That function simply loads the mask from the disk, it should be quite fast. Did you generate the agent_mask correctly on the first run?

**Comment by dodler** [comment]
i'm using full train dataset. I didn't generate agent_mask. 

Seems that it happens in case more than pipelines (not necessarily l5kit) are running.

**Comment by lucabergamini** [comment]
pipeline?

**Comment by nightmaredimple** [comment]
I've met the same problem. Using zarr.open_array("./agents_mask/0.5") can handle this. (too many tiny files)

**Comment by dodler** [comment]
pipeline i mean another  pytorch lightning train loop

**Comment by lucabergamini** [comment]
> pipeline i mean another pytorch lightning train loop

This has never been tested with PTL, so I can't guarantee it works there :(

**Comment by lucabergamini** [comment]
I'm closing this for now as we don't officially support PTL (yet)
