### ISSUE TITLE
Unexpected behaviour of visualisation script

### ISSUE THREAD

**Issue by AdamJochna** [lyft/l5kit#185]
![download](https://user-images.githubusercontent.com/12698392/97114480-057dec00-16f1-11eb-85e3-adef44dd48b6.png)

I don't know why but since few days/weeks function draw_trajectory does not correctly visualise vehicle targets.

**Comment by cvramanan** [comment]
If i try to run draw_trajectory function the error below pops up 
`/kaggle/usr/lib/lyft_l5kit_unofficial_fix/l5kit/visualization/utils.py in draw_trajectory(on_image, positions, rgb_color, radius, yaws)
     70         for pos in positions:
     71             pred_waypoint = pos[:2]
---> 72             cv2.circle(on_image, tuple(pred_waypoint.astype(np.int)), radius, rgb_color, -1)
     73 
     74 

TypeError: Argument 'radius' is required to be an integer`

I'm running the code in kaggle notebook.

**Comment by cvramanan** [comment]
The order of parameters has been changed in the draw_trajectory method.

Updated prams order : 

def draw_trajectory(
    on_image: np.ndarray,
    positions: np.ndarray,
    rgb_color: Tuple[int, int, int],
    radius: int = 1,
    yaws: Optional[np.ndarray] = None,
)

This worked for me
draw_trajectory(image, positions_pixels, (255, 0, 255),1,data["target_yaws"])

**Comment by lucabergamini** [comment]
> I don't know why but since few days/weeks function draw_trajectory does not correctly visualise vehicle targets.

I think this is an issue with coordinates frames, which version of l5kit are you using? Can you post here your trajectory visualisation code?

**Comment by lucabergamini** [comment]
I'll close this for now, let me know if you're still experiencing the issue though.
