### ISSUE TITLE
AgentDataset and EgoDataset mapping

### ISSUE THREAD

**Issue by suryajayaraman** [lyft/l5kit#186]
Hi,

This is more of helping me out question rather than issue. This is related to this [kaggle discussion](https://www.kaggle.com/c/lyft-motion-prediction-autonomous-vehicles/discussion/178323). 

Idea is to find the rationale behind raster size selection. It was suggested in the discussion to use the agent's velocity to determine the raster size required. If instead, we can use the agent's target position directly, it'd be more concrete. Since the raster image has the ego vehicle fixed at [0.25, 0.5] of the image, I thought of transforming the agent's target position trajectory to ego vehicle coordinate system.

But for doing this transformation, we need the ego vehicle coordinate and yaw angle in the world coordinates (present in centroid and yaw keys of EgoDataset) and world coordinates of the agent target position (in AgentDataset). Is there any mapping already available (we can iterate over timestamps and ids, still is there a easier solution?) which maps instances of AgentDataset map to those in EgoDataset? Like first 50 in AgentDataset are belong to 1st instance in EgoDataset. Or I am missing something important?

**Comment by lucabergamini** [comment]
If I've understood correctly you should be able to pull it off by using the `get_frame_indices` function in the `AgentDataset`. That gives you the indices in the AgentDataset itself for that given frame. The Ego information for that frame can be retrieved from the `EgoDataset` by indexing at that frame, something like this:

```python
frame_idx = 0
agent_indices = agent_dt.get_frame_indices(frame_idx)  # this function is slow, but there is a branch with an improved version
agents = [agent_dt[idx] for idx in agent_indices]
ego_info = ego_dt[frame_idx]  # this is the ego for those agents
```
Note this works on Dataset, not DataLoader (sadly)

Let me know if this helps you!

**Comment by suryajayaraman** [comment]
Thanks @lucabergamini ,  will try it out and get back. If possible, can you name which branch you were referring to as the improved one?

**Comment by lucabergamini** [comment]
Hey @suryajayaraman,
sure! the branch is [this one](https://github.com/lyft/l5kit/tree/lberg/speed-up-getframeindices-2). You may not need it, it depends on the number of accesses.

**Comment by lucabergamini** [comment]
Note, that branch has been merged into master :) 
I'm closing this, but feel free to reopen it if you need further assistance
