### ISSUE TITLE
Cannot find file "sample.zarr"

### ISSUE THREAD

**Issue by D-Niermann** [lyft/l5kit#190]
Hello,

I have downloaded the prediction data set and extracted the following files: "aerial_map.tar", "semantic_map.tarr", "training1-1.tar", "training1-2.tar" and "validate.tar".

I got every file and folder that is displayed in your Readme, except the "sample.zarr". 
I cannot look into the tar files with winRar, where should this "sample.zarr" be located ?

When I start an example script, I get the according error about the missing sample.zarr

**Comment by lucabergamini** [comment]
Hey, 
you can find the sample dataset link [here](https://self-driving.lyft.com/level5/download/). You need to register but it's quick :) Alternatively, you can also find it in the [kaggle competition page](https://www.kaggle.com/c/lyft-motion-prediction-autonomous-vehicles/data) under `scenes`

**Comment by D-Niermann** [comment]
> Hey,
> you can find the sample dataset link [here](https://self-driving.lyft.com/level5/download/). You need to register but it's quick :) Alternatively, you can also find it in the [kaggle competition page](https://www.kaggle.com/c/lyft-motion-prediction-autonomous-vehicles/data) under `scenes`

Thanks, I found it today myself, stupid me! I just overlooked the one file (and my college actually downloaded the files for me, so I didn't double check thoroughly enough)
