### ISSUE TITLE
Different rasterizations?

### ISSUE THREAD

**Issue by yousef-xailient** [lyft/l5kit#195]
In the paper, it is mentioned that one is able to use the software kit to rasterize the image in different ways as attached below. I could rasterize in the format of the image on the right, but I have not been able to do so with the style on the left. Would appreciate if someone could elaborate how I could do that?
![Screenshot from 2020-11-10 13-05-58](https://user-images.githubusercontent.com/57377547/98618758-f1bfc000-2355-11eb-8b93-edd5c3e3f528.png)

**Comment by lucabergamini** [comment]
Hi @yousef-xailient 
We provide semantic and satellite rasterisation right now. The leftmost rasteriser features lanes orientation encoded as different colours, but apart from that it's exactly the same as the one on the right. That function is still not available and I don't have an ETA rn.
