### ISSUE TITLE
[Bug?] Dataset provides speed by peeking into the future

### ISSUE THREAD

**Issue by pascal-pfeiffer** [lyft/l5kit#197]
In agent_sampling.py, the speed is calculated from future frames:
`"speed": np.linalg.norm(future_vels_mps[0]),`

In my opinion this is a design fault, and speed should be calculated from the last velocity vector in the history. 

In the current state this should not be used as a training input.

**Comment by lucabergamini** [comment]
Your observation is absolutely correct. In practice, we measured the error for the AV itself and it was less than 0.5%. I will fix it in the future, but it's not considered a priority right now
