### ISSUE TITLE
filter_agents_by_track_id simplification

### ISSUE THREAD

**Issue by louis925** [lyft/l5kit#201]
https://github.com/lyft/l5kit/blob/41197693335c0259fc84d2fba7d239c842cc06d6/l5kit/l5kit/data/filter.py#L70
Any reason why this line in `filter_agents_by_track_id` is not as simple as
```python
return agents[agents["track_id"] == track_id]
```
?

**Comment by lucabergamini** [comment]
I'd say probably not, just legacy code :) I'll change it and see if it still passes tests.

**Comment by lucabergamini** [comment]
Tracked in #202, I've also added tests to check it's working correctly. I'll close this for now
