### ISSUE TITLE
Error in the direction of the velocities in `agent_sampling`

### ISSUE THREAD

**Issue by joseluisvaz** [lyft/l5kit#215]
I realized than in `agent_sampling` the velocities are calculated using `np.diff(x)`. Given that the convention is to have the `history_*` data backwards in time the velocity vector computed points in the opposite direction. This should then be `-np.diff(x)`.

Is there a reason that this was computed this way? or is it a bug?

**Comment by lucabergamini** [comment]
> Is there a reason that this was computed this way? or is it a bug?

Probably a bug, can you take a look @yawei-ye ?

**Comment by joseluisvaz** [comment]
another problem that I found is that while computing the velocities using `np.diff`. The equation used to compute the target velocities is `v(t)  = (x(t+1) - x(t)) / ts` which is correct (solving for v(t) from euler integration). but when the velocities of the history (which goes backwards) are computed then the equation used is `v(t) = (x(t) - x(t-1)) / ts` which adds inconsistency and could add some unwanted noise when using RNN models. 

Another problem is that in the case of incomplete sequences of the form:
`[001111100]` the velocity computed using the `np.diff` will be `[0100000100]`. I have noticed that this causes a lot of problems when dealing with RNN imitative models that take the speed as input.

**Comment by yawei-ye** [comment]
> another problem that I found is that while computing the velocities using `np.diff`. The equation used to compute the target velocities is `v(t) = (x(t+1) - x(t)) / ts` which is correct (solving for v(t) from euler integration). but when the velocities of the history (which goes backwards) are computed then the equation used is `v(t) = (x(t) - x(t-1)) / ts` which adds inconsistency and could add some unwanted noise when using RNN models.
> 
> Another problem is that in the case of incomplete sequences of the form:
> `[001111100]` the velocity computed using the `np.diff` will be `[0100000100]`. I have noticed that this causes a lot of problems when dealing with RNN imitative models that take the speed as input.

Hi @joseluisvaz, sorry for the late reply and thanks for pointing out the BUG and here is the fix: https://github.com/lyft/l5kit/pull/295
We are going to release new data format which read speed from raw sensor data directly and it will solve the incomplete sequence issue.
