### ISSUE TITLE
Prediction Dataset Subsets

### ISSUE THREAD

**Issue by govvijaycal** [lyft/l5kit#231]
Hello,

I wanted to check the relationship between train.zarr and train_full.zarr.  Are they disjoint datasets or is train.zarr a subset of train_full.zarr?  I'm curious since, if these are two disjoint sets, it would be helpful to use train.zarr as a "validation" set and validation.zarr as a "test" set.

Thanks!

**Comment by pascal-pfeiffer** [comment]
train.zarr is a subset of train_full.zarr

**Comment by lucabergamini** [comment]
correct, `train.zarr` is the first part of `train_full.zarr`.
