### ISSUE TITLE
Lane Centerline Information

### ISSUE THREAD

**Issue by govvijaycal** [lyft/l5kit#232]
Hello,

I saw that in the recent release, there is a MapAPI.get_lane_as_interpolation function that provides the lane centerline as a set of XYZ points.

Also, I noticed a comment about the Boundary type in the road_network.proto file that:
"The ordering of the lane boundary vertices is expected to be consistent with the ordering of the road segment vertices."

I am wondering if I can assume the XYZ points, then, are ordered based on the orientation of the lane: i.e. you can just use the yaw of the vector between points to estimate the lane direction.  Or are these unordered such that this approach is unreliable (could be opposing the lane direction)?

Thanks!

**Comment by lucabergamini** [comment]
Yes, there is a notion of lane direction encoded in the order of the points inside the polyline. However, this is not currently used (e.g. in the rasteriser), so we have not tested it thoroughly.

In the rasteriser case, this information could be encoded as the colour of the lane for example

**Comment by govvijaycal** [comment]
Yes, I made a custom rasterizer that uses the nuscenes approach of changing the color based on the relative yaw angle.  It seems to work fine from the limited rasterized frames I looked at - although I think there are some bidirectional lanes where the colors overlap.  

Thanks for the help!
