### ISSUE TITLE
ChuckedDataset has no attribute `get_scene_dataset`

### ISSUE THREAD

**Issue by FrancescoMandru** [lyft/l5kit#270]
I'm running my tests inside my Dockerfile with l5kit version 1.2.0 And I get this error message when I try to call `get_scene_dataset` but I saw that on the source code in github there is the function so what do you think about this issue? Which can be the problem?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-ab6e443dd629> in <module>
----> 1 zarr_dataset.get_scene_dataset(10)

AttributeError: 'ChunkedDataset' object has no attribute 'get_scene_dataset'
```

**Comment by lucabergamini** [comment]
`get_scene_dataset` has been moved to `ChunkedDataset` only recently. It was not there in `v1.2.0`. 
You should be able to call it on an `EgoDataset`

**Comment by FrancescoMandru** [comment]
Hi thanks for your reply, actually i was looking to do the following:

Given a scene, I would like to retrieve all the frames related to that one, the agents and the traffic lights info, which should be all the information available in the dataset

**Comment by lucabergamini** [comment]
two options:

1. use `get_scene_dataset` on `EgoDataset` and then extract the resulting dataset
2. use the filter functions from `l5kit.data` (`get_agents_slice_from_frames, get_frames_slice_from_scenes, get_tl_faces_slice_from_frames`)

e.g
```python
frames = dataset.frames[get_frames_slice_from_scenes(scene_idx)]
agents_slice = get_agents_slice_from_frames(*frames[[0,-1]])
agents = dataset.agents[agents_slice]
... # similar for tls
```

may have some typos, I've not tested

**Comment by FrancescoMandru** [comment]
Really appreciate it thanks. I understood the difference between `EgoDataset` and `AgentDataset`, basically the former contains the information from the point of view of the car which takes the measurements while the latter contains the informations of the agents. This divides the problem in 2 tasks

- Predict the motion of the agents
- Given the predicted motion of the agents, predict the motion of the ego vehicle, this sounds a bit strange to me, as the Ego vehicle should know its path.

Correct me if I'm wrong, thanks

**Comment by lucabergamini** [comment]
this is a bit unrelated to this issue but:

`EgoDataset`: iterate over the SDV annotations;
`AgentDataset`: iterate over other agents annotations (from their point of view);

I'm not sure what you end goal is but for planning the former is enough, while you can use the latter for tasks such as prediction. If you want to get SDV and agents information for the same frame, that's a little tricky to do (frames have variable number of agents so we can't easily stick everything in a torch `Dataloader` as the collate would fail)
