### ISSUE TITLE
Visualize agent motion

### ISSUE THREAD

**Issue by FrancescoMandru** [lyft/l5kit#272]
I'm trying to use the same code for Ego dataset with Agent dataset to visulize the motion of the agent but something wrong happening, its probably due to the fact that I'm misunderstanding something. I tought the Agent and Ego classes were identical. 

https://user-images.githubusercontent.com/43784964/115042657-ff184200-9ed3-11eb-8158-aa087c4a6585.mov

Here is the code:

```
def animate_solution(images, timestamps=None):
    def animate(i):
        changed_artifacts = [im]
        im.set_data(images[i])
        if timestamps is not None:
            time_text.set_text(timestamps[i])
            changed_artifacts.append(im)
        return tuple(changed_artifacts)

    
    fig, ax = plt.subplots()
    im = ax.imshow(images[0])
    if timestamps is not None:
        time_text = ax.text(0.02, 0.95, "", transform=ax.transAxes)

    anim = animation.FuncAnimation(fig, animate, frames=len(images), interval=60, blit=True)
    
    # To prevent plotting image inline.
    plt.close()
    return anim

def plot_scene_motion(dataset, scene_idx):
    scene = dataset.get_scene_dataset(scene_idx)
    print(scene)
    indexes = range(len(dataset.get_scene_indices(scene_idx)))
    
    images = []
    
    for idx in indexes:
        frame = scene[idx]
        img = frame["image"].transpose(1, 2, 0)
        rst_img = scene.rasterizer.to_rgb(img)
        #target_positions_pixels = transform_points(frame["target_positions"] + frame["centroid"][:2], 
                                                   #frame["world_to_image"])
        
        center_in_pixels = np.asarray(cfg["raster_params"]["ego_center"]) * cfg["raster_params"]["raster_size"]
        traj = transform_points(frame["target_positions"], frame["raster_from_agent"])
        draw_trajectory(rst_img, traj, TARGET_POINTS_COLOR)
        clear_output(wait=True)
        images.append(PIL.Image.fromarray(rst_img[::-1]))
        
    return images
```

I think that the problem may come from the fact that for every frame in each scene there are different agents and I'm not following the same one, so the code can't be just copied but I need a refinement

**Comment by lucabergamini** [comment]
> I think that the problem may come from the fact that for every frame in each scene there are different agents and I'm not following the same one, so the code can't be just copied but I need a refinement

Yes, that's correct. The `AgentDataset` iterates over all (a subset tbh) agents. You can use the `track_id` attribute if you want to skip other agents in the for loop, but there is no easy way of getting only and all the output for just a single agent
