### ISSUE TITLE
How to filter the number of samples based on the frame history/future

### ISSUE THREAD

**Issue by FrancescoMandru** [lyft/l5kit#285]
I wonder if there is any method to filter the Ego / Agent dataset based on the number of history / future frames. If I set in the `.yaml` file and in the `.py` file the number of frames I get always the same number (4039527) regardless of my settings:

```python
## BASE ROOT OF DATASET USED FOR LOCAL DATA MANAGER
os.environ["L5KIT_DATA_FOLDER"] = "my_path"

## LOAD THE CONFIGURATOR
cfg = load_config_data("./config.yaml")
cfg['model_params']['history_num_frames'] = 10
## INITIALLIZE THE CLASS OF THE PATHS
dm = LocalDataManager()

# BUILD THE RASTERIZER
rasterizer = build_rasterizer(cfg, dm)

## RETUNR THE PATH REQUIRED
path = dm.require('scenes/train.zarr')

## OPEN THE ZARR FILE
zarr = ChunkedDataset(path).open()

## BUILD TRAIN DATALOADER
dataset = EgoDataset(cfg, zarr, rasterizer)
agent_dataset = AgentDataset(cfg, zarr, rasterizer)
```

**Comment by lucabergamini** [comment]
you will need to change [this line](https://github.com/lyft/l5kit/blob/0aa8de6f4c93c8e1e6b6b163dd50978c3653880c/l5kit/l5kit/dataset/agent.py#L29). for the `AgentDataset` to control the generated data.
