### ISSUE TITLE
visualizer folder is missing

### ISSUE THREAD

**Issue by L4zyy** [lyft/l5kit#288]
I use pip to install l5kit (version 1.3.0) and the visualizer folder in the visualization folder is missing. I wonder if it's a bug or it's due to I am changed the source of pip?

**Comment by lucabergamini** [comment]
Guess that's what happens when you forget to add the `__init__.py` in a folder lol.

I'll fix it and push another release, thanks for raising this up!

In the meantime, you can try to use the master at the same SHA by cloning the repo and doing the manual installation

**Comment by L4zyy** [comment]
> Guess that's what happens when you forget to add the `__init__.py` in a folder lol.
> 
> I'll fix it and push another release, thanks for raising this up!
> 
> In the meantime, you can try to use the master at the same SHA by cloning the repo and doing the manual installation

OK, thank you for the great works ^ ^
