### ISSUE TITLE
Problem with rotation in custom dataset class

### ISSUE THREAD

**Issue by FrancescoMandru** [lyft/l5kit#290]
I'm dealing with  a custom class for my problem which simplify my life. It doesn't change anything and I call it after `EgoDataset` invocation and before loading the final result into a data loader. 

```python
class TransformDataset(Dataset):
    def __init__(self, dataset, cfg):
        self.cfg = cfg
        self.dataset = dataset
        self.W = self.cfg['raster_params']['raster_size'][0]
        self.H = self.cfg['raster_params']['raster_size'][1]
    def __getitem__(self, index):
        batch = self.dataset[index]
        return self.transform(batch)

    def __len__(self):
        return len(self.dataset)

    # Here batch is just 1 element
    def transform(self, batch):

        return (batch["image"].astype(np.float32),
                batch["target_positions"].astype(np.float32),
                batch["target_availabilities"].astype(np.float32),
                batch['history_positions'].astype(np.float32),
                batch['history_yaws'].astype(np.float32),
                batch['target_yaws'].astype(np.float32),
                batch['target_velocities'].astype(np.float32),
                batch['history_velocities'].astype(np.float32),
                batch["centroid"].astype(np.float32),
                batch["world_to_image"].astype(np.float32)
                )
```

The reference code is here https://github.com/d-eremeev/SC-GAN/blob/971c169899bd76beee532bcbc8620370a3906f61/utils.py#L400. Theysaid to keep attention for newest versions of l5kit and I removed the changes of coordinates that they have done because probably in the previous versions there were some bugs which now are ok. 

However, during a training session I noticed something wrong, maybe I missed something about the trajectory rotation? They seems to be flipped.

![e0-b2230](https://user-images.githubusercontent.com/43784964/119233845-18dc2300-bb2b-11eb-9f76-a08e83173932.jpg)
![e2-b6350](https://user-images.githubusercontent.com/43784964/119233848-1a0d5000-bb2b-11eb-8cc0-55d8471f99d6.jpg)
![e4-b12020](https://user-images.githubusercontent.com/43784964/119233849-1aa5e680-bb2b-11eb-80ce-b72fba2d2fea.jpg)

In the last one it is also visible a double ground truth trajectory.

**Comment by lucabergamini** [comment]
it might be (and it's very speculative) an issue with the flag `set_origin_to_bottom` in the config. Have you tried to invert it? I'm positive about trajectories being well aligned in master, so it looks like you're doing a wrong transformation somewhere..

**Comment by FrancescoMandru** [comment]
@lucabergamini  Here's the core code before plotting the results, the history and the ground truth. I tried to find the bug but without success. Tell me if something is not clear

```python
  gen_batch = predictor(image, actor_state, noise) #Network prediction

  xy = gen_batch[batch_id].cpu().detach().numpy()  # trajectory
  

  # We want trajectories in image frame of reference, but all trajectories are given in agents FoR
  # Trajectories are already properly rotated (this consideration was true for their code where they rotated the trajectories, you # 
 # can see it on the link that I have provided in the initial post)
  W = cfg['raster_params']['raster_size'][0]
  # agent's position (in pixels)
  agent_position_image = np.array([cfg['raster_params']['ego_center'][0] * W,
                                   cfg['raster_params']['ego_center'][1] * W])

  # transform to pixels by division on r and then translate
  r = cfg['raster_params']['pixel_size'][0]
  target_positions_pixels_pred = agent_position_image + xy/r  # (target_size, 2)
  target_positions_pixels_history = agent_position_image + history_positions[batch_id].cpu().numpy()/r
  target_positions_pixels_future = agent_position_image + target_positions[batch_id].cpu().numpy()/r
```

Also I report another possible bug, sometimes the ground truth trajectory goes out of the rasterized image:

![download](https://user-images.githubusercontent.com/43784964/119385226-237eef80-bcc6-11eb-9133-291e2b9efb82.png)

**Comment by FrancescoMandru** [comment]
@lucabergamini I found how to fix it but there is somethinh which I'm not able to explain it. Looking at the last code i provided here I have done the following changes:

```python

(image, target_positions, target_availabilities,
 history_positions, history_yaws, target_yaws, 
 target_velocities, history_velocities, centroid, 
 world_to_image, world_from_agent, raster_from_world, raster_from_agent) = batch

actor_state = (history_positions, history_yaws)

batch_size = image.shape[0]
noise_dim = cfg['generator']['noise_dim']

# generate batch of predictions
noise = torch.normal(size=(batch_size, noise_dim), mean=0.0, std=1.0, 
                     dtype=torch.float32, device=cfg['device'])

gen_batch = predictor(image, actor_state, noise)

xy = gen_batch[batch_id].cpu().detach().numpy()  # trajectory

target_positions_pixels_future = transform_points(target_positions[batch_id].cpu().numpy(),
                                                  raster_from_agent[batch_id].cpu().numpy())

target_positions_pixels_history = transform_points(history_positions[batch_id].cpu().numpy(),
                                                   raster_from_agent[batch_id].cpu().numpy())

target_positions_pixels_pred = transform_points(xy, raster_from_agent[batch_id].cpu().numpy())
    
```

This works and the trajectory are now correct (Correct me if you think that this is strange). However I would like to apply this transformation in the `TransformDataset` class I provided before, but when I do that the results are totally wrong. This is weird as the target and the history trajectory are not touched during the rest of the code. Any thoughts?

**Comment by FrancescoMandru** [comment]
@lucabergamini the problem is that the model I'm using works with an older version of l5kit (don't know which one) but this probably can help you. When they have to plot the trajectories and the predictions they do the following:

```python
gen_batch = predictor(image, actor_state, noise)

xy = gen_batch[batch_id].cpu().detach().numpy()  # trajectory

W = cfg['raster_params']['raster_size'][0]
# agent's position (in pixels)
agent_position_image = np.array([cfg['raster_params']['ego_center'][0] * W,
                                 cfg['raster_params']['ego_center'][1] * W])

# transform to pixels by division on r and then translate
r = cfg['raster_params']['pixel_size'][0]
target_positions_pixels_pred = agent_position_image + xy/r  # (target_size, 2)
target_positions_pixels_history = agent_position_image + history_positions[batch_id].cpu().numpy()/r
target_positions_pixels_future = agent_position_image + target_positions[batch_id].cpu().numpy()/r
```

And the trajectories are mirrored as you can see in the images above. I wonder which is the simplest way to apply the right rotation to the raw trajectories, I would like to do that on my transform dataset class.

**Comment by lucabergamini** [comment]
> because now the orientation seems correct, the only thing is that sometimes the trajectory (ground truth and predicted are ouside the image and it is not perfectly centered.

In general the transform will only convert the coordinates to the destination space but it won't apply any clipping. So it's possible to have trajectories overspilling I would say.

Regarding the centre I would expect them to be centred on Y..



> with an older version of l5kit

A lot of things have changed, so it's perfectly possible that you're getting weird behaviours if you're using a different version of L5Kit

**Comment by FrancescoMandru** [comment]
>> In general the transform will only convert the coordinates to the destination space but it won't apply any clipping. So it's possible to have trajectories overspilling I would say.

So this is an expected behaviour? 

>> A lot of things have changed, so it's perfectly possible that you're getting weird behaviours if you're using a different version of L5Kit

Yes and I'm using the latest one, the only thing is that the model was built taking into consideration an older version so the input representation is a bit different and as they reported:

> There were some troubles with rotation angle for history/target positions in l5kit dataset which required additional change of coordinates in code. This transformation should be included in later versions of l5kit, which leads to small changes in transform method of TransformDataset class.

So I'm trying to adapt the input with the one needed by the model. It's almost done, I have some troubles only with the rotation and I tried to fix it with the approach in my previous comment, is it enough in your opinion? Am I missing something?

**Comment by lucabergamini** [comment]
> So is this an expected behaviour?
> 
> >

yeah, definitely. It's just a visual issue I suspect

**Comment by FrancescoMandru** [comment]
@lucabergamini The version used in the network I'm trying is l5kit==1.0.6. 

and this is my adaptation for the angle.

> @lucabergamini the problem is that the model I'm using works with an older version of l5kit (don't know which one) but this probably can help you. When they have to plot the trajectories and the predictions they do the following:
> 
> ```python
> gen_batch = predictor(image, actor_state, noise)
> 
> xy = gen_batch[batch_id].cpu().detach().numpy()  # trajectory
> 
> W = cfg['raster_params']['raster_size'][0]
> # agent's position (in pixels)
> agent_position_image = np.array([cfg['raster_params']['ego_center'][0] * W,
>                                  cfg['raster_params']['ego_center'][1] * W])
> 
> # transform to pixels by division on r and then translate
> r = cfg['raster_params']['pixel_size'][0]
> target_positions_pixels_pred = agent_position_image + xy/r  # (target_size, 2)
> target_positions_pixels_history = agent_position_image + history_positions[batch_id].cpu().numpy()/r
> target_positions_pixels_future = agent_position_image + target_positions[batch_id].cpu().numpy()/r
> ```
> 
> And the trajectories are mirrored as you can see in the images above. I wonder which is the simplest way to apply the right rotation to the raw trajectories, I would like to do that on my transform dataset class. I can't just use `transform_points` because I need coordinates in their original values as the network needs them in that way. My attempt is the following:
> 
> ```python
> batch['target_positions'][:,1] =  cfg['ego_center'][1] - batch['target_positions'][:,1] #cfg['ego_center'][1] = 0.5
> batch['history_positions'][:,1] = cfg['ego_center'][1] - batch['history_positions'][:,1]
> ```
> 
> is it resonable in your opinion or I totally missing it? because now the orientation seems correct, the only thing is that sometimes the trajectory (ground truth and predicted are ouside the image and it is not perfectly centered.
> 
> ![e0-b100](https://user-images.githubusercontent.com/43784964/119720098-d9367380-be69-11eb-9000-27fec66d4885.jpg)
> 
> Sometimes some frames are very weird:
> ![bug](https://user-images.githubusercontent.com/43784964/119820099-67a20800-bef1-11eb-8420-894ea8c175dc.jpg)

**Comment by lucabergamini** [comment]
This does not seem to change the angles but the positions. 

What you should do is:
- use an RT matrix to transform positions;
- correct the yaw (trajectories only) by adding/subtracting the reference angle

Don't subtract/add positions in general, as you're not taking into account the rotation angle by doing it. It may work for some spaces, but will fail eventually.

If what you're after is a flip on X, there is a [flag](https://github.com/lyft/l5kit/blob/0aa8de6f4c93c8e1e6b6b163dd50978c3653880c/examples/planning/config.yaml#L48) which will correctly flip the RT matrix for you

**Comment by FrancescoMandru** [comment]
@lucabergamini  Ok I removed that part of code and it seems that setting the `flag` to False has flipped the trajectories accordingly. A problem remain for some frames which I don't understand why it happens. Maybe it's just a visual bug. 

[e0-b120.jpg.pdf](https://github.com/lyft/l5kit/files/6610873/e0-b120.jpg.pdf)
[e0-b450.jpg.pdf](https://github.com/lyft/l5kit/files/6610874/e0-b450.jpg.pdf)

Sometimes half of the trajectory seems to be flipped and also inverted but this not happens everytime as you can see from here:

![e0-b110](https://user-images.githubusercontent.com/43784964/121061865-b474c100-c7c4-11eb-934a-43c651a803ff.jpg)

and this behaviour really confuses me. I reattach the part of code that I use in order to plot the results, the history and the ground truth.

```python
gen_batch = predictor(image, actor_state, noise)

xy = gen_batch[batch_id].cpu().detach().numpy()  # trajectory

W = cfg['raster_params']['raster_size'][0]
# agent's position (in pixels)
agent_position_image = np.array([cfg['raster_params']['ego_center'][0] * W,
                                 cfg['raster_params']['ego_center'][1] * W])

# transform to pixels by division on r and then translate
r = cfg['raster_params']['pixel_size'][0]
target_positions_pixels_pred = agent_position_image + xy/r  # (target_size, 2)
target_positions_pixels_history = agent_position_image + history_positions[batch_id].cpu().numpy()/r
target_positions_pixels_future = agent_position_image + target_positions[batch_id].cpu().numpy()/r
```

**Comment by lucabergamini** [comment]
is there any reason why you're not using `raster_from_agent` or `raster_from_world` here to get the pixel coordinates?

Anyway, if you want to clip the coordinates in raster space you just need to apply something like `np.clip`, e.g:
```python
coords = np.arange(100).reshape(50,2) # assuming XY
W, H = 25, 45
coords  = np.clip(coords, a_min=(0,0), a_max=(W, H))
```

**Comment by FrancescoMandru** [comment]
@lucabergamini I ied to use `raster_from_agent` or `raster_from_world` but probably I misunderstood their meaning . The clip is smart and I don't know why I didn't think about that, m fault. Really Tthanks Luca

**Comment by lucabergamini** [comment]
np @FrancescoMandru, can we close this then?
