### ISSUE TITLE
[Suggestion] Do NOT name the key of relative state_index as 'frame_index' in the return of AgentDataset

### ISSUE THREAD

**Issue by dongb5** [lyft/l5kit#291]
It is very confused (at least for me) that whether it is the absolute index of frame or the relative index in a scene, because `frame_index` is used as the absolute index in some other functions, such as functions in `data/filter.py`.

**Comment by lucabergamini** [comment]
thanks for the suggestion. I don't have the bandwidth to rename this in the whole codebase right now, but maybe in the future I'll take a look into doing it
