### ISSUE TITLE
history velocities calculation mistake?

### ISSUE THREAD

**Issue by KhushalB** [lyft/l5kit#294]
In agent_sampling.py, for the history velocities calculation in line 93:
`history_positions_diff_m = np.diff(history_positions_m, axis=0)` should be -np.diff since history positions are stored backwards in time starting with the current position first.

**Comment by lucabergamini** [comment]
@yawei-ye is this behaviour intended or is it a bug?

from what I can see from the code we compute diff in the future as:
```
(t_+1) - t
```

and in the past as:
```
(t_-1) - t
```

**Comment by yawei-ye** [comment]
> @yawei-ye is this behaviour intended or is it a bug?
> 
> from what I can see from the code we compute diff in the future as:
> 
> ```
> (t_+1) - t
> ```
> 
> and in the past as:
> 
> ```
> (t_-1) - t
> ```

Yes it is a bug, here is the fix: https://github.com/lyft/l5kit/pull/295

**Comment by lucabergamini** [comment]
thanks @yawei-ye , I've approved it!

@KhushalB please use master after #295 is merged if you need the correct value for speed
