### ISSUE TITLE
semantic map coordinate system doesn't fit the perception dataset

### ISSUE THREAD

**Issue by theRealNicktchopper** [lyft/l5kit#303]
Hi,

thank you for the cool toolkit. It really eases working with the Lyft dataset. I have a question regarding the combination of the perception dataset with the semantic map from the prediction dataset. I want to use the RGB frontal view images from the perception dataset along with the corresponding poses (ego_pose of vehicle) combined with the map from the prediction dataset. However, I noticed that after transforming the coordinates of the map elements from the semantic map into the global coordinate system, that they still look "weird" in comparison to the ground truth ego_vehicle poses from the perception dataset. I guess, that the reference points for the semantic map and the ego poses from the perception dataset is not the same, i.e. they live in different coordiante systems even though it is named the "global coordinate system" in both cases. Is that true? If yes, can you please tell me how and where to acquire this additional information to be able to use the semantic map for the perception dataset?

Best

**Comment by lucabergamini** [comment]
Hey @theRealNicktchopper 


> they live in different coordiante systems even though it is named the "global coordinate system" in both cases. Is that true? If yes, can you please tell me how and where to acquire this additional information to be able to use the semantic map for the perception dataset?

The two datasets were generated by different team starting from (potentially) different data. As such, I'm not really able to help you with that. Merging the two may be possible, but it was not a design goal when we opensourced l5kit

**Comment by theRealNicktchopper** [comment]
Hey Luca,

alright, thanks for the quick response.

**Comment by nnsriram97** [comment]
Thank you for the dataset. Just to clarify, currently, it's not possible to use HD map data in prediction dataset with perception dataset right? I want to obtain lane centerline and crosswalk coordinates for the vehicle pose in the perception dataset

**Comment by lucabergamini** [comment]
Hi @nnsriram97 

The best answer I can give you is that "nobody has tried". It was not something we had in mind when we designed the prediction dataset.
