### ISSUE TITLE
where to download meta.json file?

### ISSUE THREAD

**Issue by DanqingZ** [lyft/l5kit#309]
Hi,

When I am running the visualize_data notebook. I have the error: 
```
FileNotFoundError: meta.json is not present in local data folder /tmp/l5kit_data
```
I have downloaded all available datasets from https://level-5.global/data/prediction/, but I didn't see the meta.json file. Could you let me know where can I download it? Thanks.

**Comment by TrinhTuanHung2021** [comment]
You can download this file on the website. I don't remember the exact location, but I'm sure it's on the website

**Comment by DanqingZ** [comment]
The following subsets are available:
Sample dataset (51 MB)
Training dataset - Part 1/2 (8.4 GB)
Training dataset - Part 2/2 (70 GB)
Validation dataset (8.2 GB)
Aerial Map (2 GB)
Semantic Map (3 MB)

**Comment by lucabergamini** [comment]
Hi @DanqingZ ,

the `meta.json` is shipped in the `semantic_map.tar` archive. Just copy it one level up and that should fix the error
