### ISSUE TITLE
RangeValidator thresholds clarification

### ISSUE THREAD

**Issue by FrancescoMandru** [lyft/l5kit#316]
In the closed-loop evaluation it is specified a threshold which triggers the metric, taking into consideration the error.    
 
```
:param min_value: minimum value allowed (inclusive)
:param max_value: maximum value allowed (inclusive)
```

Is this threshold in meteres? For example if `max_value=4`, does it means that when the predicted trajectory deviates from the annotated one more than 4 meters, it will trigger?

**Comment by lucabergamini** [comment]
@perone can you help with this question?

**Comment by perone** [comment]
Thanks for the question @FrancescoMandru, the threshold in the `RangeValidator` doesn't have a unit and depends on the metric it is operating. For instance, if you are computing the `RangeValidator` on top of the collisions metric, then the threshold means number of collisions, however, if you are using `RangeValidator` on top of a displacement error, then it is in meters. It all boils down to which metric you specify when instantiating the `RangeValidator`.
