### ISSUE TITLE
Dataset directory

### ISSUE THREAD

**Issue by rttariverdi67** [lyft/l5kit#321]
Hi guys, I don't see how the directory must be look like, I mean the dataset where should be located, lets say I use sample dataset.

**Comment by rttariverdi67** [comment]
Hi guys, I don't see how the directory must be look like, I mean the dataset where should be located, lets say I use sample dataset.

**Comment by lucabergamini** [comment]
Hi @rttariverdi67 
please take a look [at this page](https://lyft.github.io/l5kit/overview.html) for the expected dataset structure. 

You don't have to store the dataset in a particular path, as the base path in configurable either from the json config or from the notebooks

**Comment by lenargasimov** [comment]
> Привет@rttariverdi67 пожалуйста, взгляните [на эту страницу](https://lyft.github.io/l5kit/overview.html) для ожидаемой структуры набора данных.
> 
> Вам не нужно хранить набор данных по определенному пути, так как базовый путь можно настроить либо из конфигурации json, либо из записных книжек.
![Снимок экрана от 2022-10-31 10-01-33](https://user-images.githubusercontent.com/48679704/198950092-fe663575-cb2b-417f-ba2f-fcec0a1de764.png)

After clicking on your link.
Please provide up to date information.
