### ISSUE TITLE
Project Page Stable Baselines3

### ISSUE THREAD

**Issue by araffin** [lyft/l5kit#331]
Hello,

nice project =)

We would be also interested if you could do a pull request on [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) where you add your project to the [documentation](https://stable-baselines3.readthedocs.io/en/master/misc/projects.html) (project section) ;)

**Comment by lucabergamini** [comment]
@theDebugger811 @perone I think this one is for you guys :)

**Comment by araffin** [comment]
closed by https://github.com/DLR-RM/stable-baselines3/pull/665
