### ISSUE TITLE
SimNet: Sample an initial state by cGANs

### ISSUE THREAD

**Issue by KP-Zhang** [lyft/l5kit#334]
Hi, thank you for your paper and code.

In your paper "SimNet: Learning Reactive Self-driving Simulations from Real-world Observations", Initial states are sampled by conditional generative adversarial networks (cGANs). However, I can not find the cGANs code in your repository. Did I miss anything? Can you inform me where to find the cGANs in your code?

Thank you for your attention.

**Comment by lucabergamini** [comment]
Hey @KP-Zhang 

Because the GAN part is not strictly required for neither training nor validation, we decided to not include it in the open-source release, but just release the essential component.

This may change in the future but for now we don't have enough resource to release this code.
