### ISSUE TITLE
SimNet: How do you calculate the reactivity between the ego and surrounding agents?

### ISSUE THREAD

**Issue by KP-Zhang** [lyft/l5kit#335]

**Comment by lucabergamini** [comment]
Hi @KP-Zhang 

If you're referring to the metric in `Table I `, that one was computed on an artificial evaluation set where the AV was manually stopped in front of a simulated/replayed agent.

**Comment by KP-Zhang** [comment]
Hi @laizhenhuazack . Thank you for your reply. It is very helpful.
