### ISSUE TITLE
Question about the dynamic function in Ackerman steering model

### ISSUE THREAD

**Issue by MARMOTatZJU** [lyft/l5kit#363]
In the following lines of the dynamic function, why the step interval of the dynamic system is not shown (e.g. step interval == 0,1 in case where the dynamic function steps at 10 Hz)?

https://github.com/lyft/l5kit/blob/4dc4ee5391479bb71f0b373f39c316f9eef5a961/l5kit/l5kit/kinematic/ackerman_steering_model.py#L144-L147

**Comment by yawei-ye** [comment]
Hi, good question. 
Here the unit for `v`, `steer` `acc` are per step, this is why we do not need to consider the frequency
e.g: `[v] = meter per step`
