### ISSUE TITLE
Data_format for Agents

### ISSUE THREAD

**Issue by pch9520** [lyft/l5kit#57]
Like you say in data_format.md
```
AGENT_DTYPE = [
    ("centroid", np.float64, (2,)),
    ("extent", np.float32, (3,)),
    ("yaw", np.float32),
    ("velocity", np.float32, (2,)),
    ("track_id", np.uint64),
    ("label_probabilities", np.float32, (len(LABELS),)),
]
```
What's the meaning of extent ?
I guess it's the agent's height, width and length ?
But I extract the data in secen[0] :

frame_id | timestamp | agent_x | agent_y | agent_ex1 | agent_ex2 | agent_ex3 | agent_yaw | agent_velx | agent_vely | agent_id | agent_category
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 1.26E+18 | 665.0342 | -2207.51 | 4.391328812 | 1.813830376 | 1.590975761 | 1.016675115 | 0 | 0 | 1 | CAR
1 | 1.26E+18 | 666.9965 | -2204.96 | 0.586505592 | 1.266370177 | 0.380691528 | 0.986888647 | 0 | 0 | 1 | CAR
2 | 1.26E+18 | 667.0374 | -2204.88 | 0.58669126 | 1.267707825 | 0.38143602 | 1.007894516 | 0.235175833 | 0.37267229 | 1 | CAR
3 | 1.26E+18 | 667.2947 | -2204.42 | 0.586929798 | 1.269182086 | 0.381702363 | 0.999890804 | 1.01263988 | 1.74916482 | 1 | CAR
4 | 1.26E+18 | 667.9021 | -2203.44 | 0.589754522 | 1.271379709 | 0.383637488 | 0.996144176 | 2.294893503 | 3.804159403 | 1 | CAR
5 | 1.26E+18 | 668.7579 | -2202.07 | 0.600590885 | 1.271674395 | 0.385867119 | 0.993598878 | 3.528813839 | 5.801221848 | 1 | CAR
6 | 1.26E+18 | 669.5693 | -2200.51 | 0.601163328 | 1.272772908 | 0.386420727 | 0.99629432 | 4.276067257 | 7.43839407 | 1 | CAR
7 | 1.26E+18 | 669.9974 | -2199.76 | 0.601163328 | 1.272772908 | 0.386420727 | 0.995513678 | 4.276094437 | 7.438437939 | 1 | CAR
8 | 1.26E+18 | 670.4583 | -2199.02 | 0.601163328 | 1.272772908 | 0.386420727 | 0.994767904 | 4.275854111 | 7.438612461 | 1 | CAR
9 | 1.26E+18 | 670.9053 | -2198.28 | 0.601163328 | 1.272772908 | 0.386420727 | 0.993965983 | 4.276028156 | 7.43853426 | 1 | CAR
10 | 1.26E+18 | 671.3424 | -2197.54 | 0.601163328 | 1.272772908 | 0.386420727 | 0.993202209 | 4.275919914 | 7.4386096 | 1 | CAR
11 | 1.26E+18 | 671.7809 | -2196.83 | 0.601163328 | 1.272772908 | 0.386420727 | 0.991961718 | 4.279360294 | 7.436638832 | 1 | CAR
12 | 1.26E+18 | 672.2151 | -2196.1 | 0.601163328 | 1.272772908 | 0.386420727 | 0.991313756 | 4.278395653 | 7.437198639 | 1 | CAR
13 | 1.26E+18 | 672.6445 | -2195.36 | 0.601163328 | 1.272772908 | 0.386420727 | 0.990654171 | 4.277519703 | 7.437705994 | 1 | CAR
14 | 1.26E+18 | 673.081 | -2194.63 | 0.601163328 | 1.272772908 | 0.386420727 | 0.989976883 | 4.276776791 | 7.43813467 | 1 | CAR
15 | 1.26E+18 | 673.4843 | -2193.88 | 0.601163328 | 1.272772908 | 0.386420727 | 0.989197731 | 4.276790619 | 7.438127995 | 1 | CAR
16 | 1.26E+18 | 673.9106 | -2193.15 | 0.601163328 | 1.272772908 | 0.386420727 | 0.988506138 | 4.27615118 | 7.43849659 | 1 | CAR

Parameters agent_ex1, agent_ex2 and agent_ex3 for extent[0], extent[1] and extent[2] vary over time .
I feel confused .
And where can I find the definition of coord system ? Does 'centroid[0]' means x value and which axis is x axis ?
I'm looking forward for your reply !
Thank you very much !

**Comment by lucabergamini** [comment]
Hi @pch9520, we're planning to release a doc section specifically on coordinates systems, so a lot of your questions will be answered with more details there.



> Parameters agent_ex1, agent_ex2 and agent_ex3 for extent[0], extent[1] and extent[2] vary over time .

As you correctly guessed, those are width, length and height. They are computed from our perception module, so small changes are expecte. When an agent first appears in the scene the extent is often not accurate, but the estimation should get better as it moves around the recording car. Also, the estimation is much less reliable for agents that are very far from the recording car. We have a function that's automatically called when you work with `AgentDataset` that takes care of removing unreliable agents (extent variation and distance from the recording car are checked there among other things)




> And where can I find the definition of coord system ? Does 'centroid[0]' means x value and which axis is x axis ?

All coordinates in the `zarr` are in meters, so `centroid` is a pair (x,y). The origin of this system is located in PAO. We will release a doc section with more information about that

**Comment by pch9520** [comment]
OK, thanks for your reply, I will wait for your doc section !

**Comment by lucabergamini** [comment]
Awesome, I'll close this for now, but feel free to reopen it if you need further information
