### ISSUE TITLE
Is there any way I can get the traffic light status while passing junctions?

### ISSUE THREAD

**Issue by huliang2016** [lyft/l5kit#61]
such as when the traffic light is red or green and how long will it last?

**Comment by lucabergamini** [comment]
Hi @huliang2016, 
Traffic light status is still not there but we're working on it atm! 
I don't have an ETA yet, but it's regarded as a high priority.

**Comment by lucabergamini** [comment]
Update on this:
TF support is being developed in #74

**Comment by huliang2016** [comment]
Thanks for the new feature.
I think if I want to use this new feature, I must redownload the dataset?

**Comment by lucabergamini** [comment]
The feature is still not finished and it's being developed actively
The data will be updated in the new dataset release.

**Comment by huliang2016** [comment]
ok, thanks~

**Comment by patilrajeevs** [comment]
Hi @lucabergamini  , is the TL data set released? The code in the example is still not working with the latest samples.zarr. Any other work around to get the example notebook working?

**Comment by lucabergamini** [comment]
Hey @patilrajeevs, should be online in a matter of hours :)

**Comment by lucabergamini** [comment]
The dataset is online on [kaggle](https://www.kaggle.com/c/lyft-motion-prediction-autonomous-vehicles/overview) and we're working to update the links on the lyft's website

**Comment by lucabergamini** [comment]
Dataset is now online also on [lyft's website](https://self-driving.lyft.com/level5/download/)
