### ISSUE TITLE
Are there any plans to release lane centerlines as part of the semantic map?

### ISSUE THREAD

**Issue by wqi** [lyft/l5kit#67]
I've been playing around with the Lyft prediction dataset for the past couple days and have been really impressed with the volume of data and slick implementation of scene rasterization in l5kit. However, I think the dataset could benefit from alternative forms of information about the semantic map, such as lane centerlines and connectivity. 

While the current dataset does include lane boundaries, it is missing lane centerlines - an important piece of the puzzle that is provided in both the Argoverse and NuScenes prediction datasets. In the absence of such information, it becomes more difficult to directly apply vector and graph-based forecasting models for comparison across datasets.

Are there currently any plans to release lane centerlines or connectivity graphs in future releases of the dataset?

Thanks!

**Comment by lucabergamini** [comment]
Hi @wqi, thanks for using our toolkit!

I took a quick look at the [proto](https://github.com/lyft/l5kit/blob/6b8e9cadfd03559f0438f4fc3930045f2ecfeb0d/l5kit/l5kit/data/proto/road_network.proto#L414) and the Lane is defined there by its left and right boundaries only. That means we cannot simply read the centerline but we need to compute it at run-time (it shouldn't be that difficult though).

The semantic map API will be greatly expanded in the upcoming months, so I expect this feature to land in master at some point, but I don't have an ETA yet.

**Comment by johnwlambert** [comment]
@wqi We provide simple Python/numpy-based utilities to [extract a centerline from lane boundaries](https://github.com/argoai/argoverse-api/blob/master/argoverse/utils/interpolate.py#L51) (and vice versa, from [centerline to lane boundaries](https://github.com/argoai/argoverse-api/blob/master/argoverse/utils/centerline_utils.py#L42) ) in the `argoverse-api` -- might be useful for your use case here.

**Comment by lucabergamini** [comment]
Centerline are currently in a PR and will be included at some point in the next release :)
