### ISSUE TITLE
Lack of  file meta.json

### ISSUE THREAD

**Issue by flclain** [lyft/l5kit#75]
In the agent_motion_config.yaml line 37:  dataset_meta_key: "meta.json"
But I can't find meta.json in the page https://self-driving.lyft.com/level5/download/
Could you tell me where to download the file meta.json, thank you.

**Comment by lucabergamini** [comment]
Hi @flclain, that file replaces a hard-coded matrix and will be shipped with a new dataset release. As such, we're currently falling back to the hard-coded matrix in the meantime (see [here](https://github.com/lyft/l5kit/blob/6b8e9cadfd03559f0438f4fc3930045f2ecfeb0d/l5kit/l5kit/rasterization/rasterizer_builder.py#L91) ) and will notify users when the switch is finalised.

So the short answer is: you don't need to worry about that right now :) However, if you're instead experiencing a runtime error, please let me know.

**Comment by happinesslz** [comment]
@lucabergamini  I meet the same error: lack of "meta.json" file.

**Comment by lucabergamini** [comment]
HI @happinesslz , is it a warning or a strict error you're getting?

**Comment by happinesslz** [comment]
Thanks for your reply! After update the code, now the error is solved. But I download the prediction datasets for official website. Unzip these files and organize the  files as follows:
```
|-- aerial_map
|-- sample.zarr
|-- semantic_map
|-- train_0.zarr
|-- train_1.zarr
`-- train_2.zarr
```
The organization is different from the README. How to convert to:
```
  +- sample_scenes/
  +- scenes/
  +- aerial_map/
  +- semantic_map/
```
Could you please provide the introduction for  the "sample_scenes" and  "scenes" files.  (What contains in "sample_scenes" and  "scenes" files). Looking forward to your reply. Thanks!

**Comment by happinesslz** [comment]
@lucabergamini  Thanks for your reply! After update the code, now the error is solved. But I download the prediction datasets for official website. Unzip these files and organize the files as follows:
```
|-- aerial_map
|-- sample.zarr
|-- semantic_map
|-- train_0.zarr
|-- train_1.zarr
`-- train_2.zarr
```
The organization is different from the README. How to convert to:
```
  +- sample_scenes/
  +- scenes/
  +- aerial_map/
  +- semantic_map/
```
Could you please provide the introduction for the "sample_scenes" and "scenes" files. (What contains in "sample_scenes" and "scenes" files). Looking forward to your reply. Thanks!

**Comment by lucabergamini** [comment]
Hi @happinesslz 
here is the structure:
```
prediction-dataset/
  +- sample_scenes/
        +- sample.zarr
  +- scenes/
        +- train_0.zarr
        +- train_1.zarr
        +- train_2.zarr
  +- aerial_map/
  +- semantic_map/
```

I'll add it in master through #110 later. Also, we're releasing the dataset v1.1 in the upcoming days, so be ready for some other changes to the local structure :)  I'll try to document them better this time though
