### ISSUE TITLE
Timestamps for the frames seem off

### ISSUE THREAD

**Issue by Shreyagupta21** [lyft/l5kit#90]
Hello @lucabergamini,
The timestamps for each of the frames seem a little off.  For the first few frames, I got 1256678902801892606, 1256678902901714926, and 1256678903001499246 which were all sometime in October 27, 2009.  The rest of the timestamps are similarly off.  What am I doing wrong? 

My code:
frames = zarr_dataset.frames
for idx_coord, idx_data in enumerate(tqdm(range(len(frames)), desc="getting centroid to plot trajectory")):
    time = zarr_dataset.frames[idx_data][0]
    print(time)

The converter I used:
https://www.epochconverter.com/ 

Thanks,
Shreya

**Comment by lucabergamini** [comment]
Hi @Shreyagupta21 , we have triaged this and found an issue with timestamp for frames.
While `start_time` and `end_time` for the scene are correct, `timestamp` for frames are off. 

We will correct this issue in the upcoming new release of the dataset

**Comment by Shreyagupta21** [comment]
Hello @lucabergamini,
Is the relationship between the timestamps accurate even though the time stamps themselves aren't? I'm not sure if I phrased that well so an example is that if the timestamps for frames 1 and 2 are are 10 and 11, even if the timestamp is wrong is the time in between them still 1?

**Comment by lucabergamini** [comment]
yes, @Shreyagupta21 the frames are still ordered properly and the temporal differences are valid.
I'll close this for now, but feel free to reopen it if things don't add up
