### ISSUE TITLE
Can only access 96 scenes but the website says there are 170,000

### ISSUE THREAD

**Issue by Shreyagupta21** [lyft/l5kit#91]
Hello,
On the website it says that there are 170,000 scenes, but when I use the code given in the visualization_data example to find the number of scenes it says there are only 96.  Is there some other way of accessing the remaining 169,904 scenes?

**Comment by lucabergamini** [comment]
Hi @Shreyagupta21, the visualisation notebook [load the sample.zarr](https://github.com/lyft/l5kit/blob/80530d6920eebd636e41e30793bcef1110a39f7b/examples/visualisation/visualisation_config.yaml#L47) as dataset. This is only a small sample dataset for visualisation purposes. You can replace the path to point to one of the training set zarr, which is going to be much larger.
